version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "1000:80" # Проброс порта 1000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3050:3050" # Проброс порта 3055 на 3050

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "4000:80"

  authoriation:
    build:
      context: .
      dockerfile: Dockerfile.authorization
    ports:
      - "2000:80"

  onlinepayment:
    build:
      context: .
      dockerfile: Dockerfile.onlinepayment
    ports:
      - "5000:80"